
//////////mongodb

###
GET http://localhost:6060/api/users
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MjM5NGEzMWRjOTBiNWI4MWVjOTllMyIsImVtYWlsIjoiT3l1a2E1QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGZ3VXpiUDVlTFlVNHZpM0k5M0JXQ3VKd3p2VXplQnBPRm5KQ0lhSm5uUEZwTEZBMXUzamtLIiwiaXNBZG1pbiI6ZmFsc2UsIm9yZGVySWRzIjpbXSwiZmF2SXRlbSI6W10sImNyZWF0ZWRBdCI6IjIwMjMtMDMtMjlUMDE6MzA6MTEuMjQ5WiIsInVwZGF0ZWRBdCI6IjIwMjMtMDMtMjlUMDE6MzA6MTEuMjQ5WiIsIl9fdiI6MH0sImlhdCI6MTY4MDA1MzQxNCwiZXhwIjoxNjgwMjI2MjE0fQ.UloLQ0S3ZU-CvVQ8BJAOp7PIVf7yEs5Pqixn1O39zNY


###
POST http://localhost:6060/api/users/register
Content-Type: application/json

{
  "email":"Oyuka5@gmail.com",
  "password":"qweqwe123456"
}



###
POST http://localhost:6060/api/users/login
Content-Type: application/json

{
  "email":"Oyuka5@gmail.com",
  "password":"qweqwe123456"
}


###
GET http://localhost:6060/api/users/64128f2e7f21780d581f695a
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MjM5NGEzMWRjOTBiNWI4MWVjOTllMyIsImVtYWlsIjoiT3l1a2E1QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGZ3VXpiUDVlTFlVNHZpM0k5M0JXQ3VKd3p2VXplQnBPRm5KQ0lhSm5uUEZwTEZBMXUzamtLIiwiaXNBZG1pbiI6ZmFsc2UsIm9yZGVySWRzIjpbXSwiZmF2SXRlbSI6W10sImNyZWF0ZWRBdCI6IjIwMjMtMDMtMjlUMDE6MzA6MTEuMjQ5WiIsInVwZGF0ZWRBdCI6IjIwMjMtMDMtMjlUMDE6MzA6MTEuMjQ5WiIsIl9fdiI6MH0sImlhdCI6MTY4MDA1MzQxNCwiZXhwIjoxNjgwMjI2MjE0fQ.UloLQ0S3ZU-CvVQ8BJAOp7PIVf7yEs5Pqixn1O39zNY

###
PUT http://localhost:6060/api/users/64128f2e7f21780d581f695a
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MjM5NGEzMWRjOTBiNWI4MWVjOTllMyIsImVtYWlsIjoiT3l1a2E1QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGZ3VXpiUDVlTFlVNHZpM0k5M0JXQ3VKd3p2VXplQnBPRm5KQ0lhSm5uUEZwTEZBMXUzamtLIiwiaXNBZG1pbiI6ZmFsc2UsIm9yZGVySWRzIjpbXSwiZmF2SXRlbSI6W10sImNyZWF0ZWRBdCI6IjIwMjMtMDMtMjlUMDE6MzA6MTEuMjQ5WiIsInVwZGF0ZWRBdCI6IjIwMjMtMDMtMjlUMDE6MzA6MTEuMjQ5WiIsIl9fdiI6MH0sImlhdCI6MTY4MDA1MzQxNCwiZXhwIjoxNjgwMjI2MjE0fQ.UloLQ0S3ZU-CvVQ8BJAOp7PIVf7yEs5Pqixn1O39zNY
{
    "firstName": "Bold"
}

###
DELETE http://localhost:6060/api/users/64128f2e7f21780d581f695a
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MjM5NGEzMWRjOTBiNWI4MWVjOTllMyIsImVtYWlsIjoiT3l1a2E1QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGZ3VXpiUDVlTFlVNHZpM0k5M0JXQ3VKd3p2VXplQnBPRm5KQ0lhSm5uUEZwTEZBMXUzamtLIiwiaXNBZG1pbiI6ZmFsc2UsIm9yZGVySWRzIjpbXSwiZmF2SXRlbSI6W10sImNyZWF0ZWRBdCI6IjIwMjMtMDMtMjlUMDE6MzA6MTEuMjQ5WiIsInVwZGF0ZWRBdCI6IjIwMjMtMDMtMjlUMDE6MzA6MTEuMjQ5WiIsIl9fdiI6MH0sImlhdCI6MTY4MDA1MzQxNCwiZXhwIjoxNjgwMjI2MjE0fQ.UloLQ0S3ZU-CvVQ8BJAOp7PIVf7yEs5Pqixn1O39zNY

###
POST http://localhost:6060/api/users
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MjM5NGEzMWRjOTBiNWI4MWVjOTllMyIsImVtYWlsIjoiT3l1a2E1QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGZ3VXpiUDVlTFlVNHZpM0k5M0JXQ3VKd3p2VXplQnBPRm5KQ0lhSm5uUEZwTEZBMXUzamtLIiwiaXNBZG1pbiI6ZmFsc2UsIm9yZGVySWRzIjpbXSwiZmF2SXRlbSI6W10sImNyZWF0ZWRBdCI6IjIwMjMtMDMtMjlUMDE6MzA6MTEuMjQ5WiIsInVwZGF0ZWRBdCI6IjIwMjMtMDMtMjlUMDE6MzA6MTEuMjQ5WiIsIl9fdiI6MH0sImlhdCI6MTY4MDA1MzQxNCwiZXhwIjoxNjgwMjI2MjE0fQ.UloLQ0S3ZU-CvVQ8BJAOp7PIVf7yEs5Pqixn1O39zNY

{
    "firstName": "Test122",
    "lastName": "Test1e12",
    "email": "test",
    "address": "Test1",
    "phoneNumber": 12345,
    "userName": "Test",
    "password": "Test1",
    "isAdmin": false,
    "orderIds": ["ssa" , "fdsd"],
    "favItem": ["dsa"]
}
