

###
GET http://localhost:6060/api/orderDet
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MjM5NGEzMWRjOTBiNWI4MWVjOTllMyIsImVtYWlsIjoiT3l1a2E1QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGZ3VXpiUDVlTFlVNHZpM0k5M0JXQ3VKd3p2VXplQnBPRm5KQ0lhSm5uUEZwTEZBMXUzamtLIiwiaXNBZG1pbiI6ZmFsc2UsIm9yZGVySWRzIjpbXSwiZmF2SXRlbSI6W10sImNyZWF0ZWRBdCI6IjIwMjMtMDMtMjlUMDE6MzA6MTEuMjQ5WiIsInVwZGF0ZWRBdCI6IjIwMjMtMDMtMjlUMDE6MzA6MTEuMjQ5WiIsIl9fdiI6MH0sImlhdCI6MTY4MDA1MzQxNCwiZXhwIjoxNjgwMjI2MjE0fQ.UloLQ0S3ZU-CvVQ8BJAOp7PIVf7yEs5Pqixn1O39zNY

###
GET http://localhost:6060/api/orderDet/
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MjM5NGEzMWRjOTBiNWI4MWVjOTllMyIsImVtYWlsIjoiT3l1a2E1QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGZ3VXpiUDVlTFlVNHZpM0k5M0JXQ3VKd3p2VXplQnBPRm5KQ0lhSm5uUEZwTEZBMXUzamtLIiwiaXNBZG1pbiI6ZmFsc2UsIm9yZGVySWRzIjpbXSwiZmF2SXRlbSI6W10sImNyZWF0ZWRBdCI6IjIwMjMtMDMtMjlUMDE6MzA6MTEuMjQ5WiIsInVwZGF0ZWRBdCI6IjIwMjMtMDMtMjlUMDE6MzA6MTEuMjQ5WiIsIl9fdiI6MH0sImlhdCI6MTY4MDA1MzQxNCwiZXhwIjoxNjgwMjI2MjE0fQ.UloLQ0S3ZU-CvVQ8BJAOp7PIVf7yEs5Pqixn1O39zNY

###
PUT http://localhost:6060/api/orderDet/
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MjM5NGEzMWRjOTBiNWI4MWVjOTllMyIsImVtYWlsIjoiT3l1a2E1QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGZ3VXpiUDVlTFlVNHZpM0k5M0JXQ3VKd3p2VXplQnBPRm5KQ0lhSm5uUEZwTEZBMXUzamtLIiwiaXNBZG1pbiI6ZmFsc2UsIm9yZGVySWRzIjpbXSwiZmF2SXRlbSI6W10sImNyZWF0ZWRBdCI6IjIwMjMtMDMtMjlUMDE6MzA6MTEuMjQ5WiIsInVwZGF0ZWRBdCI6IjIwMjMtMDMtMjlUMDE6MzA6MTEuMjQ5WiIsIl9fdiI6MH0sImlhdCI6MTY4MDA1MzQxNCwiZXhwIjoxNjgwMjI2MjE0fQ.UloLQ0S3ZU-CvVQ8BJAOp7PIVf7yEs5Pqixn1O39zNY


{
    "productIds": [""]
}


###
POST http://localhost:6060/api/orderDet
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MjM5NGEzMWRjOTBiNWI4MWVjOTllMyIsImVtYWlsIjoiT3l1a2E1QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGZ3VXpiUDVlTFlVNHZpM0k5M0JXQ3VKd3p2VXplQnBPRm5KQ0lhSm5uUEZwTEZBMXUzamtLIiwiaXNBZG1pbiI6ZmFsc2UsIm9yZGVySWRzIjpbXSwiZmF2SXRlbSI6W10sImNyZWF0ZWRBdCI6IjIwMjMtMDMtMjlUMDE6MzA6MTEuMjQ5WiIsInVwZGF0ZWRBdCI6IjIwMjMtMDMtMjlUMDE6MzA6MTEuMjQ5WiIsIl9fdiI6MH0sImlhdCI6MTY4MDA1MzQxNCwiZXhwIjoxNjgwMjI2MjE0fQ.UloLQ0S3ZU-CvVQ8BJAOp7PIVf7yEs5Pqixn1O39zNY


{
    "orderId": "64239a1b239273f92c777ca9",
    "productIds": ["641bb84216aa4e6d203ccd03"],
    "totalPrice": 100,
    "requiredDate": "2022-12-31"
}

###
DELETE http://localhost:60606/api/orderDet/
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MjM5NGEzMWRjOTBiNWI4MWVjOTllMyIsImVtYWlsIjoiT3l1a2E1QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGZ3VXpiUDVlTFlVNHZpM0k5M0JXQ3VKd3p2VXplQnBPRm5KQ0lhSm5uUEZwTEZBMXUzamtLIiwiaXNBZG1pbiI6ZmFsc2UsIm9yZGVySWRzIjpbXSwiZmF2SXRlbSI6W10sImNyZWF0ZWRBdCI6IjIwMjMtMDMtMjlUMDE6MzA6MTEuMjQ5WiIsInVwZGF0ZWRBdCI6IjIwMjMtMDMtMjlUMDE6MzA6MTEuMjQ5WiIsIl9fdiI6MH0sImlhdCI6MTY4MDA1MzQxNCwiZXhwIjoxNjgwMjI2MjE0fQ.UloLQ0S3ZU-CvVQ8BJAOp7PIVf7yEs5Pqixn1O39zNY

