

###
GET http://localhost:6060/api/orders
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MjA1MmE2YzQ5OGRjZDUxYzY0NGMxMyIsImVtYWlsIjoiT3l1a2E1QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJHNMOTFwQWRwLm5lWVdYeUVqUnNiSU94UmtzZDdUTERHSC8vVTdveFJsdXpHSHJTLnlqTm1TIiwiaXNBZG1pbiI6ZmFsc2UsIm9yZGVySWQiOltdLCJmYXZJdGVtIjpbXSwiY3JlYXRlZEF0IjoiMjAyMy0wMy0yNlQxNDoxMTo1MC44NThaIiwidXBkYXRlZEF0IjoiMjAyMy0wMy0yNlQxNDoxMTo1MC44NThaIiwiX192IjowfSwiaWF0IjoxNjc5ODQwMDQ2LCJleHAiOjE2ODAwMTI4NDZ9.72MMY2F2P1VHtOdoUX9A93Nh91okE2EKD-QVXgDC61A

###
GET http://localhost:6060/api/orders/64205496ad3a658be19095b7
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MjA1MmE2YzQ5OGRjZDUxYzY0NGMxMyIsImVtYWlsIjoiT3l1a2E1QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJHNMOTFwQWRwLm5lWVdYeUVqUnNiSU94UmtzZDdUTERHSC8vVTdveFJsdXpHSHJTLnlqTm1TIiwiaXNBZG1pbiI6ZmFsc2UsIm9yZGVySWQiOltdLCJmYXZJdGVtIjpbXSwiY3JlYXRlZEF0IjoiMjAyMy0wMy0yNlQxNDoxMTo1MC44NThaIiwidXBkYXRlZEF0IjoiMjAyMy0wMy0yNlQxNDoxMTo1MC44NThaIiwiX192IjowfSwiaWF0IjoxNjc5ODQwMDQ2LCJleHAiOjE2ODAwMTI4NDZ9.72MMY2F2P1VHtOdoUX9A93Nh91okE2EKD-QVXgDC61A



###
POST http://localhost:6060/api/orders
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MjA1MmE2YzQ5OGRjZDUxYzY0NGMxMyIsImVtYWlsIjoiT3l1a2E1QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJHNMOTFwQWRwLm5lWVdYeUVqUnNiSU94UmtzZDdUTERHSC8vVTdveFJsdXpHSHJTLnlqTm1TIiwiaXNBZG1pbiI6ZmFsc2UsIm9yZGVySWQiOltdLCJmYXZJdGVtIjpbXSwiY3JlYXRlZEF0IjoiMjAyMy0wMy0yNlQxNDoxMTo1MC44NThaIiwidXBkYXRlZEF0IjoiMjAyMy0wMy0yNlQxNDoxMTo1MC44NThaIiwiX192IjowfSwiaWF0IjoxNjc5ODQwMDQ2LCJleHAiOjE2ODAwMTI4NDZ9.72MMY2F2P1VHtOdoUX9A93Nh91okE2EKD-QVXgDC61A


{
    "UserId": "642052a6c498dcd51c644c13",
    "totalPrice": 1234,
    "requiredDate": "2022-12-31",
    "shippedDate": "2022-12-30",
    "status": "Cancelled"  
}