

///////mongodb 


###
GET http://localhost:6060/api/products


###
POST http://localhost:6060/api/products
Content-Type: application/json

{
  "productName": "String",
    "categoryIds": ["641a33a664fa75b29fa54fab"],
    "price": 1234,
    "desc": "String",
    "sale": 13,
    "color": "String",
    "isTrending": false,
    "brandIds": ["641baca75570cf603f63d116"],
    "isFav": false,
    "imgs": "String",
    "quantity":123
}

###
DELETE http://localhost:6060/api/products/641bb82c16aa4e6d203cccfe

###
PUT http://localhost:6060/api/products/
Content-Type: application/json

{
  "productName": "test1"
}



