


###
GET http://localhost:6060/api/products

###
GET http://localhost:6060/api/products/7d3be315-bbba-454b-bd5a-012539b95e8b

###
POST http://localhost:6060/api/products

###
PUT http://localhost:6060/api/products/9c73e0a6-cdc0-43d9-805a-411d364afc31
Content-Type: application/json

{
     "productName": "TEst12",
      "category": "phone",
      "price": 203,
      "desc": "bla",
      "sale": "1234567",
      "isTrending": 203,
      "quintify": "",
      "imgs": {
        "coverImg": "",
        "thumbnail": ""
      }
}


###
DELETE http://localhost:6060/api/products/1


///////mongodb 


###
GET http://localhost:6060/api/products


###
POST http://localhost:6060/api/products
Content-Type: application/json

{
  "productName": "String",
    "categoryIds": ["641a33a664fa75b29fa54fab"],
    "price": 1234,
    "desc": "String",
    "sale": 13,
    "color": "String",
    "isTrending": false,
    "brandIds": ["641baca75570cf603f63d116"],
    "isFav": false,
    "imgs": "String",
    "quantity":123
}

###
DELETE http://localhost:6060/api/products/641bb82c16aa4e6d203cccfe

###
PUT http://localhost:6060/api/products/
Content-Type: application/json

{
  "productName": "test1"
}



